name: new_quakka
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.6+7

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  audioplayers: ^6.1.0
  cached_network_image: ^3.3.1
#  carousel_slider: ^4.2.1
  cloud_firestore: ^5.2.0
  conditional_builder_null_safety: ^0.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  fancy_shimmer_image: ^2.0.3
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_credit_card: ^4.0.1
  flutter_iconly: ^1.0.2
  flutter_local_notifications: ^17.2.1+2
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1

  font_awesome_flutter: ^10.7.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  get_it: ^8.0.0
  http: ^1.2.2
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2
  intl:
  pinput: ^5.0.0
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.2
  screenshot: ^3.0.0
  share_plus: ^10.0.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  signalr_netcore: ^1.3.7
  sms_autofill: ^2.4.0
  url_launcher: ^6.3.0
  device_preview: ^1.1.0
  googleapis_auth: ^1.6.0
  flutter_paypal_payment: ^1.0.6


cupertino_icons:
shimmer:
fancy_shimmer_image:
  flutter_iconly:
  device_preview:
  flutter_localizations:
    sdk: flutter
  intl:
  cached_network_image:
  font_awesome_flutter:
  flutter_screenutil:
  flutter_bloc:
  dio:
  flutter_svg:
  image_picker:
  equatable:
  provider:
  sms_autofill:
  screenshot:
  image_gallery_saver:
  http:
  flutter_spinkit:
  freezed:
  freezed_annotation:
  get_it:
  share_plus:
  iconly:
  json_annotation:
  #  location:
  lottie:
  pinput:
  pretty_dio_logger:
  retrofit:
  shared_preferences:
  url_launcher:
  flutter_local_notifications:
  firebase_core:
  cloud_firestore:
  firebase_storage:
  firebase_messaging:
  firebase_analytics:
  conditional_builder_null_safety:
  dartz:
  flutter_credit_card:
  signalr_netcore:



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


dev_dependencies:
  retrofit_generator: ^9.1.2
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/sounds/send_message_sound.wav
    - assets/images/
    - assets/language/
    - assets/notification.wav


  fonts:
    - family: SF-Pro-Rounded-Regular
      fonts:
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 400
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 600
        - asset: assets/fonts/ubuntu/Bahij_TheSansArabic-Bold.ttf
          weight: 600

flutter_intl:
  enabled: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages